### ISSUE TITLE
Containerize the frontend

### ISSUE THREAD

**Issue by WSIContractor** [Anrop/Anrop-Frontend#38]
@Dahlgren Would is be possible to have a Dockerfile and docker-compose.yml for the Anrop-Frontend?

Thanks in Advance.

**Comment by Dahlgren** [comment]
Sure, I could add a Dockerfile for it

**Comment by Dahlgren** [comment]
I've fixed the missing Dockerfiles for the rest of our webservices more or less now, this one should be done in the next couple of days I hope :)

**Comment by WSIContractor** [comment]
Fantastic! thanks for doing that. I was wondering do you have a master arch ref diagram? I get how some of the components come together, but some others not sure about. Looking to save a little time without having to reverse engineer everything.... :-)

**Comment by Dahlgren** [comment]
Not yet, I'm mostly just moving out stuff from our old PHP based website from 2006 to the new standalone API
